
cuda:0
Traceback (most recent call last):
  File "/home/ericji3/ECE496/ECE496/src/eval_model.py", line 55, in <module>
    main()
  File "/home/ericji3/ECE496/ECE496/src/eval_model.py", line 30, in main
    model.load_state_dict(torch.load(save_path))
  File "/home/ericji3/miniconda3/envs/ECE496/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ericji3/miniconda3/envs/ECE496/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ericji3/miniconda3/envs/ECE496/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../models/2D-FACT_config1_DDPM'