cuda:0
Test Size : 3072
Traceback (most recent call last):
  File "/home/ericji3/ECE496/ECE496/src/train_model.py", line 123, in <module>
    main()
  File "/home/ericji3/ECE496/ECE496/src/train_model.py", line 33, in main
    train_loader, val_loader, test_loader = make_dataset_shadows.import_outdoor_data()
ValueError: too many values to unpack (expected 3)